# Generated by Django 5.2.7 on 2025-11-08 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Weightlifting', 'Weightlifting'), ('Cardio', 'Cardio'), ('Crossfit', 'Crossfit'), ('Yoga', 'Yoga'), ('Boxing', 'Boxing'), ('Running', 'Running'), ('Swimming', 'Swimming'), ('Tennis', 'Tennis'), ('Gymnastics', 'Gymnastics'), ('Horse Riding', 'Horse Riding'), ('Other', 'Other')], default='Weightlifting')),
                ('set', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
