# Generated by Django 5.2.7 on 2025-11-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, help_text='Nazwij swój trening, np. KLATA, NOGI...', max_length=100),
        ),
    ]
