# Generated by Django 5.2.3 on 2025-11-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('Weightlifting', 'Weightlifting'), ('Cardio', 'Cardio'), ('Crossfit', 'Crossfit'), ('Kettlebell', 'Kettlebell'), ('Yoga', 'Yoga'), ('Boxing', 'Boxing'), ('Running', 'Running'), ('Swimming', 'Swimming'), ('Tennis', 'Tennis'), ('Gymnastics', 'Gymnastics'), ('Horse Riding', 'Horse Riding'), ('Other', 'Other')], default='Weightlifting'),
        ),
    ]
